### ISSUE TITLE
Подключение приложений

### ISSUE THREAD

**Issue by Amet13** [zarkone/bachelor#2]
Привет.
Подскажи пожалуйста как ты подключаешь приложения. По примерам понять не могу.
Пробовал через 

``` latex
\append{Заголовок}
```

подключать, не выходит.
В данный момент пока все поднастраиваю под себя, вроде все получается, кроме приложений.
Пока выходит что-то типа:

``` latex
\input{inc/title} % Титул
\input{inc/0-intro} % Введение
\input{inc/1-pz} % Постановка задачи
\input{inc/2-literature} % Обзор литературных источников
\input{inc/3-topicality} % Обосновние актуальности темы и ее практической значимости
\input{inc/4-analyze} % Системный анализ
%%% Еще какие-то разделы
\input{inc/0-conclusion} % Заключение
\input{inc/0-bibliography} % Библиографический список
%%% Вот тут надо подключить приложения
```

**Comment by zarkone** [comment]
Привет! 

Что конкретно не получается \ не понятно? Для приложения пришлось создать свою команду, на самом деле это не приложения LaTeX, а просто обычно заголовки -- что-то было не так, как требуется, уже не помню детали..

Можно попробовать вставить прямо как у меня, но я думаю ты уже так пробовал)

**Comment by Amet13** [comment]
Да, по-твоему что-то не выходит, в main.tex:

``` latex
\input{inc/a-app}
```

В a-app.tex:

``` latex
\setcounter{section}{0}
\renewcommand\thesubsection{\Asbuk{section}.\arabic{subsection}}

\stepcounter{section}
\newpage
\renewcommand\thesection{\Asbuk{section}}
\renewcommand\thesubsection{\Asbuk{section}.\arabic{subsection}}

\addcontentsline{toc}{section}{Приложение \Asbuk{section} Задание на
  бакалаврскую работу} 

\append{Руководство пользователя}
```

Ругается на 13 строчку a-app.tex (там где написано \append{...}):

```
Missing number, treated as zero
```

**Comment by zarkone** [comment]
хм, до сих пор непонятно. Вот какие предположения: либо есть что-то еще в коде, либо из-за версии -- у меня Debian Stable... можно попробовать выставить в `main.tex`:

``` latex
\errorcontextlines 10000
```

А мой исходник  у тебя собирается?

**Comment by Amet13** [comment]
Да, собирается.

Ладно, пока временно сделал приложения через:

``` latex
\anonsection{Приложение А. Первое приложение}
```

**Comment by Amet13** [comment]
В принципе мне совсем мало осталось до допиливания под себя.
По сути только секции в оглавлении должны быть в верхнем регистре, и номера страниц убрать жирный шрифт.
![screenshot](https://cloud.githubusercontent.com/assets/5184847/6319271/1d667b5c-bac7-11e4-95e4-d34879d2ee91.png)

**Comment by zarkone** [comment]
:+1:
Amet Umerov writes:

> В принципе мне совсем мало осталось до допиливания под себя.
> По сути только секции в оглавлении должны быть в верхнем регистре, и номера страниц убрать жирный шрифт.
> ![screenshot](https://cloud.githubusercontent.com/assets/5184847/6319265/f16a3fca-bac6-11e4-9b72-a9878840c195.png)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zarkone/bachelor/issues/2#issuecomment-75442672

## 

Sent with my mu4e
